# Generated by Django 5.1.15 on 2026-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelayAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('avg_delay_seconds', models.FloatField(default=0.0)),
                ('max_delay_seconds', models.IntegerField(default=0)),
                ('min_delay_seconds', models.IntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('on_time_percentage', models.FloatField(default=100.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delay_analytics',
                'ordering': ['-date', 'route'],
            },
        ),
        migrations.CreateModel(
            name='FleetStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('active_vehicles', models.PositiveIntegerField(default=0)),
                ('delayed_vehicles', models.PositiveIntegerField(default=0)),
                ('average_speed_kmh', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'fleet_stats',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
