# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetstats',
            name='transport_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_stats', to='vehicles.transportmode'),
        ),
        migrations.AlterUniqueTogether(
            name='delayanalytics',
            unique_together={('route', 'date')},
        ),
    ]
