# Generated by Django 5.1.15 on 2026-09-19 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('status', models.CharField(default='MOVING', max_length=30)),
                ('occupancy_status', models.CharField(blank=True, default='MANY_SEATS_AVAILABLE', max_length=30)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_positions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('vehicle_id', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(max_length=30)),
                ('route_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='simulator', max_length=50)),
                ('payload', models.JSONField(help_text='Full normalized transport.event.v1 JSON payload.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'transport_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['vehicle_id', 'received_at'], name='transport_e_vehicle_bebd95_idx'), models.Index(fields=['mode', 'received_at'], name='transport_e_mode_ac54ee_idx')],
            },
        ),
    ]
