# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleposition',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='vehicleposition',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_pos_vehicle_e72856_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['latitude', 'longitude'], name='vehicle_pos_latitud_6a700f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['timestamp'], name='vehicle_pos_timesta_9a2a4c_idx'),
        ),
    ]
