# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stops', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='transport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='vehicles.transportmode'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['latitude', 'longitude'], name='stops_latitud_b90c44_idx'),
        ),
    ]
