# Generated by Django 5.1.15 on 2026-09-19 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('alert_type', models.CharField(choices=[('OVERSPEED', 'Overspeed Violation'), ('UNEXPECTED_STOP', 'Unexpected Vehicle Stop'), ('ROUTE_DEVIATION', 'Route Deviation'), ('LONG_DELAY', 'Excessive Delay'), ('VEHICLE_OFFLINE', 'Vehicle Signal Lost / Offline'), ('EMERGENCY', 'Vehicle Emergency Broadcast')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('header_text', models.CharField(max_length=255)),
                ('description_text', models.TextField()),
                ('cause', models.CharField(default='UNKNOWN_CAUSE', max_length=100)),
                ('effect', models.CharField(default='UNKNOWN_EFFECT', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('active_period_start', models.DateTimeField(blank=True, null=True)),
                ('active_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
