# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='affected_routes',
            field=models.ManyToManyField(blank=True, related_name='service_alerts', to='routes.route'),
        ),
    ]
