{
 "title": "2. API Performance",
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(unitransit_api_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (4xx / 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(unitransit_api_requests_total{status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "p95 API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(unitransit_api_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 (seconds)"
    }
   ]
  }
 ]
}