from django.urls import path
from apps.devops.views import (
    system_health_overview,
    service_dependency_graph,
    trigger_chaos_experiment,
    run_load_test,
    deployments_center,
    canary_action,
    incidents_center,
    centralized_logs,
    slo_and_reliability,
    error_budget_view,
    slo_experiment_view,
    feature_flags_management,
    list_workers_api,
    scale_workers_api,
    kill_worker_api,
    benchmark_history_api,
    run_benchmark_api,
    benchmark_failover_api,
    kubernetes_observability_api,
    autoscaling_experiment_api,
    rolling_deploy_api,
    rollback_experiment_api,
    canary_experiment_view,
)

urlpatterns = [
    path("health/", system_health_overview, name="devops-system-health"),
    path("service-graph/", service_dependency_graph, name="devops-service-graph"),
    path("chaos/trigger/", trigger_chaos_experiment, name="devops-chaos-trigger"),
    path("loadtest/run/", run_load_test, name="devops-loadtest-run"),
    path("deployments/", deployments_center, name="devops-deployments"),
    path("deployments/canary/", canary_action, name="devops-canary-action"),
    path("deployments/canary/experiment/", canary_experiment_view, name="devops-canary-experiment"),
    path("deployments/rollout/", rolling_deploy_api, name="devops-rolling-deploy"),
    path("deployments/rollback-experiment/", rollback_experiment_api, name="devops-rollback-experiment"),
    path("incidents/", incidents_center, name="devops-incidents"),
    path("logs/", centralized_logs, name="devops-logs"),
    path("slo/", slo_and_reliability, name="devops-slo"),
    path("error-budget/", error_budget_view, name="devops-error-budget"),
    path("slo/experiment/", slo_experiment_view, name="devops-slo-experiment"),
    path("feature-flags/", feature_flags_management, name="devops-feature-flags"),
    # Phase 3 & 3.5: Scaling Lab & Worker Orchestrator
    path("workers/", list_workers_api, name="devops-workers-list"),
    path("workers/scale/", scale_workers_api, name="devops-workers-scale"),
    path("workers/kill/", kill_worker_api, name="devops-workers-kill"),
    path("benchmark/history/", benchmark_history_api, name="devops-benchmark-history"),
    path("benchmark/run/", run_benchmark_api, name="devops-benchmark-run"),
    path("benchmark/failover/", benchmark_failover_api, name="devops-benchmark-failover"),
    # Phase 4.5: Kubernetes Observability & Autoscaling
    path("kubernetes/", kubernetes_observability_api, name="devops-kubernetes-observability"),
    path("autoscaling/experiment/", autoscaling_experiment_api, name="devops-autoscaling-experiment"),
]
