# Generated by Django 5.1.15 on 2026-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('short_name', models.CharField(max_length=30)),
                ('long_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563EB', max_length=10)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('polyline_geojson', models.JSONField(blank=True, default=dict, help_text='GeoJSON representation of the route polyline path.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['short_name'],
            },
        ),
    ]
