# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='transport_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='vehicles.transportmode'),
        ),
    ]
