# Generated by Django 5.1.15 on 2026-09-19 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaosExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('target_service', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RECOVERED', 'Recovered'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('expected_behavior', models.CharField(max_length=255)),
                ('actual_behavior', models.CharField(blank=True, max_length=255)),
                ('recovery_time_seconds', models.FloatField(blank=True, null=True)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'devops_chaos_experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.CharField(default='general', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devops_feature_flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=16)),
                ('status', models.CharField(choices=[('INVESTIGATING', 'Investigating'), ('IDENTIFIED', 'Identified'), ('MITIGATING', 'Mitigating'), ('RESOLVED', 'Resolved')], default='INVESTIGATING', max_length=16)),
                ('affected_service', models.CharField(max_length=128)),
                ('timeline', models.JSONField(default=list, help_text='List of timestamped incident events')),
                ('postmortem', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devops_incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
