# Generated by Django 5.1.15 on 2026-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic incident metrics and thresholds'),
        ),
    ]
