# Generated by Django 5.1.15 on 2026-09-19 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_incident_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_type', models.CharField(choices=[('VEHICLE_LOAD', 'Vehicle Load Scale'), ('WORKER_SCALING', 'Worker Pool Scaling')], default='VEHICLE_LOAD', max_length=32)),
                ('vehicles', models.IntegerField(default=10)),
                ('workers', models.IntegerField(default=1)),
                ('events_per_sec', models.FloatField(default=0.0)),
                ('processing_latency_ms', models.FloatField(default=0.0)),
                ('consumer_lag_sec', models.FloatField(default=0.0)),
                ('pel_count', models.IntegerField(default=0)),
                ('api_latency_ms', models.FloatField(default=0.0)),
                ('cpu_pct', models.FloatField(default=0.0)),
                ('memory_mb', models.FloatField(default=0.0)),
                ('bottleneck_identified', models.CharField(default='OPTIMAL', max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'devops_benchmarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
