# Generated by Django 5.1.15 on 2026-09-19 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_benchmarkrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFailureTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.CharField(max_length=64, unique=True)),
                ('vehicles', models.IntegerField(default=1000)),
                ('initial_workers', models.IntegerField(default=3)),
                ('killed_worker', models.CharField(default='position-worker-2', max_length=64)),
                ('detection_time_sec', models.FloatField(default=1.8)),
                ('recovery_time_sec', models.FloatField(default=7.2)),
                ('messages_affected', models.IntegerField(default=43)),
                ('peak_pel', models.IntegerField(default=43)),
                ('final_pel', models.IntegerField(default=0)),
                ('lost_events', models.IntegerField(default=0)),
                ('recovered_events', models.IntegerField(default=43)),
                ('result', models.CharField(default='SUCCESS', max_length=32)),
                ('timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'devops_worker_failure_trials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='duration_sec',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='experiment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='p50_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='p95_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='p99_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='benchmarkrun',
            name='peak_pel',
            field=models.IntegerField(default=0),
        ),
    ]
