# Generated by Django 5.1.15 on 2026-09-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='bus', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transport_modes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('license_plate', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('MOVING', 'Moving'), ('STOPPED', 'Stopped'), ('CONGESTED', 'Congested'), ('OFFLINE', 'Offline'), ('EMERGENCY', 'Emergency')], db_index=True, default='OFFLINE', max_length=30)),
                ('occupancy_status', models.CharField(choices=[('EMPTY', 'Empty'), ('MANY_SEATS_AVAILABLE', 'Many Seats Available'), ('FEW_SEATS_AVAILABLE', 'Few Seats Available'), ('STANDING_ROOM_ONLY', 'Standing Room Only'), ('FULL', 'Full'), ('NOT_ACCEPTING_PASSENGERS', 'Not Accepting Passengers')], default='MANY_SEATS_AVAILABLE', max_length=30)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('current_speed', models.FloatField(default=0.0)),
                ('current_heading', models.FloatField(default=0.0)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='routes.route')),
                ('current_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='trips.trip')),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.transportmode')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_id'],
                'indexes': [models.Index(fields=['current_latitude', 'current_longitude'], name='vehicles_current_02ff9e_idx'), models.Index(fields=['status', 'is_active'], name='vehicles_status_4ff651_idx')],
            },
        ),
    ]
