apiVersion: v1
kind: ConfigMap
metadata:
  name: unitransit-config
  namespace: unitransit
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "unitransit"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_STREAM_KEY: "transport.events"
  REDIS_GROUP_NAME: "unitransit_workers"
  SIMULATOR_VEHICLES_COUNT: "50"
  SIMULATOR_UPDATE_INTERVAL_SEC: "2.0"
  SIMULATOR_FAULT_RATE: "0.02"
