apiVersion: v1
kind: Secret
metadata:
  name: unitransit-secrets
  namespace: unitransit
type: Opaque
stringData:
  SECRET_KEY: "unitransit-k8s-prod-secret-key-replace-with-vault-or-sealed-secrets"
  POSTGRES_USER: "unitransit"
  POSTGRES_PASSWORD: "unitransit_k8s_secure_password"
